//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGymSales.Models.SmartGymMen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_ID { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string Gendar { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone_mobile { get; set; }
        public string address { get; set; }
        public string phone_home { get; set; }
        public string id_type { get; set; }
        public string id_number { get; set; }
        public string cardid { get; set; }
        public Nullable<decimal> hieght { get; set; }
        public Nullable<decimal> wieght { get; set; }
        public string notes { get; set; }
        public string pic_path { get; set; }
        public Nullable<int> block { get; set; }
        public Nullable<int> userstuffid { get; set; }
        public Nullable<int> recordstatus { get; set; }
        public Nullable<System.DateTime> recorddate { get; set; }
        public Nullable<System.TimeSpan> recordtime { get; set; }
    }
}
