//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGymSales.Models.SmartGymWomen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public int ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> offer_id { get; set; }
        public string Cardid { get; set; }
        public Nullable<decimal> Subscripcost { get; set; }
        public Nullable<decimal> moneypaied { get; set; }
        public Nullable<decimal> moneyremind { get; set; }
        public Nullable<decimal> deduct { get; set; }
        public Nullable<int> subscriptype { get; set; }
        public Nullable<int> subscrippariod { get; set; }
        public Nullable<int> pariodofoffer { get; set; }
        public Nullable<System.DateTime> S_Date { get; set; }
        public Nullable<System.DateTime> E_Date { get; set; }
        public Nullable<int> userstuffid { get; set; }
        public Nullable<int> recordstatus { get; set; }
        public Nullable<System.DateTime> recorddate { get; set; }
        public Nullable<System.TimeSpan> recordtime { get; set; }
    }
}
