//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGymSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class possibleCustmer
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> customer_id { get; set; }
        public bool is_called { get; set; }
        public int calles_count { get; set; }
        public bool is_subscribed { get; set; }
        public Nullable<int> discont_percentage { get; set; }
        public bool is_hidden { get; set; }
        public int knowledge_id { get; set; }
        public System.DateTime creaation_date { get; set; }
    
        public virtual knowledgeLookup knowledgeLookup { get; set; }
    }
}
