//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGymSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int id { get; set; }
        public int training { get; set; }
        public int reciption { get; set; }
        public int general { get; set; }
        public string comment { get; set; }
        public System.DateTime creation_date { get; set; }
        public int parent_id { get; set; }
        public string parent_id_type { get; set; }
    }
}
