//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGymSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCustomer
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> added_By_id { get; set; }
        public int addition_type_id { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> discont_percentage { get; set; }
        public bool is_called { get; set; }
        public int calles_count { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.DateTime> subscription_start_date { get; set; }
        public Nullable<System.DateTime> subscription_end_date { get; set; }
        public Nullable<int> men_forign_Key { get; set; }
        public Nullable<int> women_forign_key { get; set; }
        public System.DateTime creation_date { get; set; }
    
        public virtual AdditionLookup AdditionLookup { get; set; }
    }
}
